/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digitales.principal;

import javax.swing.JOptionPane;

/**
 *
 * @author Punto Crítiko
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group1 = new javax.swing.ButtonGroup();
        Group2 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        CheckDecimal1 = new javax.swing.JCheckBox();
        CheckBin1 = new javax.swing.JCheckBox();
        CheckOct1 = new javax.swing.JCheckBox();
        CheckHex1 = new javax.swing.JCheckBox();
        CheckBCD1 = new javax.swing.JCheckBox();
        TextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CheckDec2 = new javax.swing.JCheckBox();
        CheckBin2 = new javax.swing.JCheckBox();
        CheckOct2 = new javax.swing.JCheckBox();
        CheckHex2 = new javax.swing.JCheckBox();
        CheckBCD2 = new javax.swing.JCheckBox();
        BotonLimpiar = new javax.swing.JButton();
        BotonConvertir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        MenuManual = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Group1.add(CheckDecimal1);
        CheckDecimal1.setText("Decimal");
        CheckDecimal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckDecimal1ActionPerformed(evt);
            }
        });

        Group1.add(CheckBin1);
        CheckBin1.setText("Binario");
        CheckBin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBin1ActionPerformed(evt);
            }
        });

        Group1.add(CheckOct1);
        CheckOct1.setText("Octal");

        Group1.add(CheckHex1);
        CheckHex1.setText("Hexadecimal");

        Group1.add(CheckBCD1);
        CheckBCD1.setText("BCD");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Número Convertido:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Selecciona la Base de tu Número:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Ingresa el Número a Convertir:");

        TextField2.setEditable(false);
        TextField2.setBackground(new java.awt.Color(255, 255, 255));
        TextField2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Selecciona la Base a Convertir:");

        Group2.add(CheckDec2);
        CheckDec2.setText("Decimal");
        CheckDec2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckDec2StateChanged(evt);
            }
        });

        Group2.add(CheckBin2);
        CheckBin2.setText("Binario");

        Group2.add(CheckOct2);
        CheckOct2.setText("Octal");

        Group2.add(CheckHex2);
        CheckHex2.setText("Hexadecimal");
        CheckHex2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckHex2ActionPerformed(evt);
            }
        });

        Group2.add(CheckBCD2);
        CheckBCD2.setText("BCD");

        BotonLimpiar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonConvertir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BotonConvertir.setText("Convertir");
        BotonConvertir.setMaximumSize(new java.awt.Dimension(69, 23));
        BotonConvertir.setMinimumSize(new java.awt.Dimension(69, 23));
        BotonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConvertirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckOct1)
                            .addComponent(CheckHex1)
                            .addComponent(CheckBin1)
                            .addComponent(CheckDecimal1)
                            .addComponent(CheckBCD1))))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBin2)
                    .addComponent(CheckBCD2)
                    .addComponent(CheckHex2)
                    .addComponent(CheckDec2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(TextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckOct2)
                    .addComponent(BotonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(TextField2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CheckDec2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckBin2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckOct2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckHex2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckBCD2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(CheckDecimal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckBin1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckOct1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckHex1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckBCD1)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonLimpiar)
                    .addComponent(BotonConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        MenuOpciones.setText("Opciones");

        MenuManual.setText("Manual");
        MenuManual.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                MenuManualMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        MenuManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuManualActionPerformed(evt);
            }
        });
        MenuOpciones.add(MenuManual);

        jMenuBar1.add(MenuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuManualMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_MenuManualMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuManualMenuKeyPressed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
       TextField1.setText("");   // TODO add your handling code here:;
             TextField2.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConvertirActionPerformed
        // TODO add your handling code here:
    	System.out.println("Hola");
    	if(CheckDecimal1.isSelected() && CheckHex2.isSelected()){
    		int point=TextField1.getText().length() ;
    		String respuestaEntera;
    		String respuestaFraccion;
    		for(int i =0; i < TextField1.getText().length(); i++){
    			if(TextField1.getText().charAt(i) == '.'){
    				point=i;
    				break;
    			}
    		}
    		
    		respuestaEntera    = Conversions.CDecimalHexadecimalEntero(TextField1.getText().substring(0, point));
    		System.out.println(TextField1.getText().substring(point, TextField1.getText().length()));
    		respuestaFraccion = Conversions.CDecimalHexadecimalFraccion(TextField1.getText().substring(point + 1, TextField1.getText().length()));
    		
    		TextField2.setText(respuestaEntera + "." + respuestaFraccion);
    		
    	}
    	
    	/*if(CheckBCD1.isSelected() && CheckDec2.isSelected()){
    		int point=TextField1.getText().length() ;
    		String respuestaEntera;
    		String respuestaFraccion;
    		for(int i =0; i < TextField1.getText().length(); i++){
    			if(TextField1.getText().charAt(i) == '.'){
    				point=i;
    				break;
    			}
    		}
    		
    		//respuestaEntera    = Conversions.CBcdDecimalEntero(TextField1.getText().substring(0, point));
    		System.out.println(TextField1.getText().substring(point, TextField1.getText().length()));
    		//respuestaFraccion = Conversions.CDecimalHexadecimalFraccion(TextField1.getText().substring(point + 1, TextField1.getText().length()));
    		
    		//TextField2.setText(respuestaEntera);// + "." + respuestaFraccion);
    		
    	}*/
    	
    	
    	//BINARIO A BINARIO
    	
    	if(CheckBin1.isSelected() && CheckBin2.isSelected())
		{		
			int point=TextField1.getText().length();
			String respuestaEntera;
			String respuestaFraccion;
			
			for(int i =0; i < TextField1.getText().length(); i++){
				if(TextField1.getText().charAt(i) == '.'){
					point=i;
					break;
				}
			}
			
			respuestaEntera = TextField1.getText().substring(0, point);
    		respuestaFraccion = TextField1.getText().substring(point + 1, TextField1.getText().length());
    		TextField2.setText(respuestaEntera + "." + respuestaFraccion);  
		}		
    	
    	
    	//BINARIO A DECIMAL
    	
    	if(CheckBin1.isSelected() && CheckDec2.isSelected())
		{		
			int point=TextField1.getText().length();
			String respuestaEntera;
			String respuestaFraccion;
			int cont =0;
			for(int i =0; i < TextField1.getText().length(); i++){
				if(TextField1.getText().charAt(i) == '.'){
					point=i;
					cont=1;
					break;
				}
			}		
			try{
				if(cont == 0)
				{
					respuestaEntera = Conversions.CBinarioDecimalEntero(TextField1.getText().substring(0, point));
					TextField2.setText(respuestaEntera);
				}
				if(cont == 1)
				{
					if(TextField1.getText().substring(0, point).equals(""))
					{
						respuestaFraccion = Conversions.CBinarioDecimalFraccion(TextField1.getText().substring(point + 1, TextField1.getText().length()));
						TextField2.setText("0." + respuestaFraccion);
					}
					else
					{
						respuestaEntera = Conversions.CBinarioDecimalEntero(TextField1.getText().substring(0, point));
						respuestaFraccion = Conversions.CBinarioDecimalFraccion(TextField1.getText().substring(point + 1, TextField1.getText().length()));
						TextField2.setText(respuestaEntera + "." + respuestaFraccion);
					}
								
				}			
			}
			
			catch(Exception e)
			{
				JOptionPane.showMessageDialog(null, "El numero introducido es incorrecto");
			}
		}    	
    	
    	//BINARIO A OCTAL
    	
    	if(CheckBin1.isSelected() && CheckOct2.isSelected())
		{		
			int point=TextField1.getText().length();
			String respuestaEntera;
			String respuestaFraccion;
			int cont =0;
			for(int i =0; i < TextField1.getText().length(); i++){
				if(TextField1.getText().charAt(i) == '.'){
					point=i;
					cont=1;
					break;
				}
			}		
			try{
				if(cont == 0)
				{
					respuestaEntera = Conversions.CBinarioOctalEntero(TextField1.getText().substring(0, point));
					TextField2.setText(respuestaEntera);
				}
				if(cont == 1)
				{
					if(TextField1.getText().substring(0, point).equals(""))
					{
						respuestaFraccion = Conversions.CBinarioOctalFraccion(TextField1.getText().substring(point + 1, TextField1.getText().length()));
						TextField2.setText("0." + respuestaFraccion);
					}
					else
					{
						respuestaEntera = Conversions.CBinarioOctalEntero(TextField1.getText().substring(0, point));
						respuestaFraccion = Conversions.CBinarioOctalFraccion(TextField1.getText().substring(point + 1, TextField1.getText().length()));
						TextField2.setText(respuestaEntera + "." + respuestaFraccion);
					}
								
				}			
			}
			
			catch(Exception e)
			{
				JOptionPane.showMessageDialog(null, "El numero introducido es incorrecto");
			}
		}    	
    	  	  	
    	//BINARIO A HEXA
    	
    	if(CheckBin1.isSelected() && CheckHex2.isSelected())
		{		
			int point=TextField1.getText().length();
			String respuestaEntera;
			String respuestaFraccion;
			int cont =0;
			for(int i =0; i < TextField1.getText().length(); i++){
				if(TextField1.getText().charAt(i) == '.'){
					point=i;
					cont=1;
					break;
				}
			}		
			try{
				if(cont == 0)
				{
					respuestaEntera = Conversions.CBinarioHexaEntero(TextField1.getText().substring(0, point));
					TextField2.setText(respuestaEntera);
				}
				if(cont == 1)
				{
					if(TextField1.getText().substring(0, point).equals(""))
					{
						respuestaFraccion = Conversions.CBinarioHexaFraccion(TextField1.getText().substring(point + 1, TextField1.getText().length()));
						TextField2.setText("0." + respuestaFraccion);
					}
					else
					{
						respuestaEntera = Conversions.CBinarioHexaEntero(TextField1.getText().substring(0, point));
						respuestaFraccion = Conversions.CBinarioHexaFraccion(TextField1.getText().substring(point + 1, TextField1.getText().length()));
						TextField2.setText(respuestaEntera + "." + respuestaFraccion);
					}
								
				}			
			}
			
			catch(Exception e)
			{
				JOptionPane.showMessageDialog(null, "El numero introducido es incorrecto");
			}
		}  
    	
    }//GEN-LAST:event_BotonConvertirActionPerformed

    private void MenuManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuManualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuManualActionPerformed

    private void CheckDec2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckDec2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckDec2StateChanged

    private void CheckDecimal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckDecimal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckDecimal1ActionPerformed

    private void CheckBin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBin1ActionPerformed

    private void CheckHex2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckHex2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckHex2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
           
           
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConvertir;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JCheckBox CheckBCD1;
    private javax.swing.JCheckBox CheckBCD2;
    private javax.swing.JCheckBox CheckBin1;
    private javax.swing.JCheckBox CheckBin2;
    public static javax.swing.JCheckBox CheckDec2;
    public static javax.swing.JCheckBox CheckDecimal1;
    private javax.swing.JCheckBox CheckHex1;
    private javax.swing.JCheckBox CheckHex2;
    private javax.swing.JCheckBox CheckOct1;
    private javax.swing.JCheckBox CheckOct2;
    private javax.swing.ButtonGroup Group1;
    private javax.swing.ButtonGroup Group2;
    private javax.swing.JMenuItem MenuManual;
    private javax.swing.JMenu MenuOpciones;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
